# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WN80lxmoiohAZHT8f-seaQ_NEd5s33vU
"""

from IPython.display import HTML

shell_script = """
<div id="game-container" style="width: 800px; height: 600px; margin: 0 auto; background: #000;"></div>
<div id="score" style="position: absolute; top: 20px; left: 20px; color: white; font-family: sans-serif; font-size: 20px;">Score: 0</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script>
    const container = document.getElementById('game-container');
    const scoreElement = document.getElementById('score');

    // 1. Scene Setup
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(75, 800 / 600, 0.1, 1000);
    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setSize(800, 600);
    container.appendChild(renderer.domElement);

    // 2. Lighting
    const light = new THREE.DirectionalLight(0xffffff, 1);
    light.position.set(5, 5, 5).normalize();
    scene.add(light);
    scene.add(new THREE.AmbientLight(0x404040));

    // 3. Game Variables
    let snake = [{x: 0, y: 0, z: 0}];
    let snakeMeshes = [];
    let direction = {x: 1, y: 0, z: 0};
    let food = {x: 5, y: 5, z: 0};
    let score = 0;
    const gridSize = 20;
    const stepSize = 1;

    // Grid Helper
    const gridHelper = new THREE.GridHelper(gridSize, gridSize);
    scene.add(gridHelper);

    // 4. Snake and Food Creation
    const boxGeo = new THREE.BoxGeometry(0.9, 0.9, 0.9);
    const snakeMat = new THREE.MeshPhongMaterial({ color: 0x00ff00 });
    const foodMat = new THREE.MeshPhongMaterial({ color: 0xff0000 });

    let foodMesh = new THREE.Mesh(boxGeo, foodMat);
    scene.add(foodMesh);

    function updateSnakeMeshes() {
        // Clear old meshes
        snakeMeshes.forEach(m => scene.remove(m));
        snakeMeshes = [];

        // Create new meshes for each segment
        snake.forEach(seg => {
            const mesh = new THREE.Mesh(boxGeo, snakeMat);
            mesh.position.set(seg.x, seg.y, seg.z);
            scene.add(mesh);
            snakeMeshes.push(mesh);
        });
    }

    function moveFood() {
        food.x = Math.floor(Math.random() * (gridSize/2)) * (Math.random() < 0.5 ? 1 : -1);
        food.y = Math.floor(Math.random() * (gridSize/2)) * (Math.random() < 0.5 ? 1 : -1);
        foodMesh.position.set(food.x, food.y, food.z);
    }

    // 5. Controls (WASD for XY, QE for Z)
    document.addEventListener('keydown', (e) => {
        switch(e.key.toLowerCase()) {
            case 'w': direction = {x: 0, y: 1, z: 0}; break;
            case 's': direction = {x: 0, y: -1, z: 0}; break;
            case 'a': direction = {x: -1, y: 0, z: 0}; break;
            case 'd': direction = {x: 1, y: 0, z: 0}; break;
            case 'q': direction = {x: 0, y: 0, z: 1}; break;
            case 'e': direction = {x: 0, y: 0, z: -1}; break;
        }
    });

    // 6. Main Loop
    camera.position.z = 15;
    camera.position.y = 5;
    camera.lookAt(0,0,0);

    let lastTime = 0;
    const interval = 200; // Move every 200ms

    function animate(time) {
        requestAnimationFrame(animate);

        if (time - lastTime > interval) {
            // Calculate new head
            const newHead = {
                x: snake[0].x + direction.x,
                y: snake[0].y + direction.y,
                z: snake[0].z + direction.z
            };

            // Food collision
            if (newHead.x === food.x && newHead.y === food.y && newHead.z === food.z) {
                score += 10;
                scoreElement.innerText = "Score: " + score;
                moveFood();
            } else {
                snake.pop(); // Remove tail
            }

            snake.unshift(newHead); // Add new head
            updateSnakeMeshes();
            lastTime = time;
        }

        renderer.render(scene, camera);
    }

    moveFood();
    animate(0);
</script>
"""

HTML(shell_script)